// Static (non-interactive) infographic images, sourced from the wp repo:
// https://github.com/jonkingseestheworld/wp/tree/master/assets/img/gallery
// Each entry: label, description, tags, thumbnail (small preview for the card grid),
// full (full-resolution image shown in the lightbox on click), and bgColor (the
// poster's dominant background colour, used as the letterbox colour in the card
// so portrait/landscape posters aren't cropped — sampled from each image's corner).
// Labels/descriptions below are best-guess titles derived from filenames — edit freely.

export const staticGalleryConfig = [
  {
    id: 'tt-2023-wk28-northern-hemi-temp',
    label: 'Northern Hemisphere Temperature (TT Wk28 2023)',
    description: 'An animated TidyTuesday visualisation of Northern Hemisphere temperature trends.',
    tags: ['TidyTuesday', 'Animation', 'Trend'],
    thumbnail: '/gallery/tt20230711wk28_NorthernHemi_temp.gif',
    full: '/gallery/tt20230711wk28_NorthernHemi_temp.gif',
    bgColor: '#000000',
  },
  {
    id: 'tt-2023-wk28-global-temp',
    label: 'Global Temperature (TT Wk28 2023)',
    description: 'An animated TidyTuesday visualisation of global temperature trends.',
    tags: ['TidyTuesday', 'Animation', 'Trend'],
    thumbnail: '/gallery/tt20230711wk28_global_temp.gif',
    full: '/gallery/tt20230711wk28_global_temp.gif',
    bgColor: '#000000',
  },
    {
    id: 'tt-2023-wk17-marathon',
    label: 'Marathon (TT Wk17 2023)',
    description: 'A TidyTuesday visualisation of marathon data.',
    tags: ['TidyTuesday', 'Rank', 'Polar'],
    thumbnail: '/gallery/thumbnails/tt20230425wk17_marathon_thumb.jpg',
    full: '/gallery/tt20230425wk17_marathon.png',
    bgColor: '#13293D',
  },
    {
    id: 'jpn-airports',
    label: 'Japan Airports',
    description: 'A line-based visualisation of airports and routes across Japan.',
    tags: ['Map', 'Network', 'Graph', 'Geospatial'],
    thumbnail: '/gallery/thumbnails/2_Line_jpn_airports_thumb.jpg',
    full: '/gallery/2_Line_jpn_airports.png',
    bgColor: '#C3DBD4',
  },
  {
    id: 'passport-access-rank-2023',
    label: 'Passport Access Rank 2023',
    description: 'A ranking of global passports by the level of travel access they grant.',
    tags: ['Rank', 'Infographic'],
    thumbnail: '/gallery/thumbnails/PassportAccessRank2023_plot_thumb.jpg',
    full: '/gallery/PassportAccessRank2023_plot.png',
    bgColor: '#0e0d0d',
  },
  {
    id: 'hp-trait-similarity-network',
    label: 'Harry Potter Trait Similarity Network',
    description: 'A network diagram connecting Harry Potter characters by shared traits.',
    tags: ['Network', 'Graph', 'Similarity'],
    thumbnail: '/gallery/thumbnails/HP_trait_similarity_network_thumb.jpg',
    full: '/gallery/HP_trait_similarity_network.png',
    bgColor: '#000035',
  },
  {
    id: 'tt-2023-wk27-hist-markers',
    label: 'Historical Markers (TT Wk27 2023)',
    description: 'A TidyTuesday visualisation of historical markers.',
    tags: ['TidyTuesday', 'Map', 'Geospatial'],
    thumbnail: '/gallery/thumbnails/tt20230704wk27_hist_markers_thumb.jpg',
    full: '/gallery/tt20230704wk27_hist_markers.png',
    bgColor: '#133133',
  },
  {
    id: 'tt-2023-wk6-techstockprice',
    label: 'Tech Stock Price (TT Wk6 2023)',
    description: 'A TidyTuesday exploration of technology stock prices.',
    tags: ['TidyTuesday', 'Tech', 'Stocks', 'Trend'],
    thumbnail: '/gallery/thumbnails/tt20230207wk6_techstockprice_thumb.jpg',
    full: '/gallery/tt20230207wk6_techstockprice.png',
    bgColor: '#E5FBE5',
  },
  {
    id: 'tt-2023-wk7-hollywood-age',
    label: 'Hollywood Age (TT Wk7 2023)',
    description: 'A TidyTuesday visualisation of age trends in Hollywood.',
    tags: ['TidyTuesday', 'Table', 'gt'],
    thumbnail: '/gallery/thumbnails/tt20230214wk7_HollywoodAge_thumb.jpg',
    full: '/gallery/tt20230214wk7_HollywoodAge.png',
    bgColor: '#FFFFFF',
  },
  {
    id: 'uk-pubs-starbucks',
    label: 'UK Pubs vs Starbucks',
    description: 'A point map comparing the distribution of UK pubs and Starbucks locations.',
    tags: ['Map', 'Geospatial'],
    thumbnail: '/gallery/thumbnails/1_Point_uk_pubs_starbucks_thumb.jpg',
    full: '/gallery/1_Point_uk_pubs_starbucks.png',
    bgColor: '#011936',
  },
  {
    id: 'tech-energy-weur',
    label: 'Tech & Energy Stocks (Western Europe)',
    description: 'A look at technology and energy sector stock performance across Western Europe.',
    tags: ['Stock', 'Energy', 'Line', 'Area', 'Trend'],
    thumbnail: '/gallery/thumbnails/20220719_tech_energy_WEUR_thumb.jpg',
    full: '/gallery/20220719_tech_energy_WEUR.png',
    bgColor: '#C0C0C0',
  },
  {
    id: 'usa-artists',
    label: 'USA Artists',
    description: 'A visual exploration of artists across the United States.',
    tags: ['Flow', 'Connections'],
    thumbnail: '/gallery/thumbnails/20220927_USA_artists_thumb.jpg',
    full: '/gallery/20220927_USA_artists.png',
    bgColor: '#EEEEEE',
  },
  {
    id: 'tt-2023-wk8-br-color-uniq',
    label: 'Colour Uniqueness (TT Wk8 2023)',
    description: 'A TidyTuesday visualisation exploring colour uniqueness.',
    tags: ['TidyTuesday', 'Treemap'],
    thumbnail: '/gallery/thumbnails/tt20230221wk8_BRcolor_uniq_thumb.jpg',
    full: '/gallery/tt20230221wk8_BRcolor_uniq.png',
    bgColor: '#EFEFED',
  },
  {
    id: 'tt-2023-wk13-timezones',
    label: 'Timezones (TT Wk13 2023)',
    description: 'A TidyTuesday visualisation of global timezones.',
    tags: ['TidyTuesday', 'Map', 'Timezones', 'Geospatial'],
    thumbnail: '/gallery/thumbnails/tt20230329wk13_timezones_thumb.jpg',
    full: '/gallery/tt20230329wk13_timezones.png',
    bgColor: '#171C19',
  },
  {
    id: 'osm-birmingham',
    label: 'Birmingham OpenStreetMap',
    description: 'An OpenStreetMap-based visualisation of Birmingham, UK.',
    tags: ['OSM', 'Map'],
    thumbnail: '/gallery/thumbnails/day8_OSM_Bham_thumb.jpg',
    full: '/gallery/day8_OSM_Bham.png',
    bgColor: '#232526',
  },
];
